<?php

namespace NextX\AptGong;

class RegionCode
{
  /**
   * 전국 252개 시군구 법정동코드
   * [LAWD_CD => [sido_nm, sigungu_nm]]
   */
  const REGIONS = [
    '11110' => ['sido_nm' => '서울특별시', 'sigungu_nm' => '종로구'],
    '11140' => ['sido_nm' => '서울특별시', 'sigungu_nm' => '중구'],
    '11170' => ['sido_nm' => '서울특별시', 'sigungu_nm' => '용산구'],
    '11200' => ['sido_nm' => '서울특별시', 'sigungu_nm' => '성동구'],
    '11215' => ['sido_nm' => '서울특별시', 'sigungu_nm' => '광진구'],
    '11230' => ['sido_nm' => '서울특별시', 'sigungu_nm' => '동대문구'],
    '11260' => ['sido_nm' => '서울특별시', 'sigungu_nm' => '중랑구'],
    '11290' => ['sido_nm' => '서울특별시', 'sigungu_nm' => '성북구'],
    '11305' => ['sido_nm' => '서울특별시', 'sigungu_nm' => '강북구'],
    '11320' => ['sido_nm' => '서울특별시', 'sigungu_nm' => '도봉구'],
    '11350' => ['sido_nm' => '서울특별시', 'sigungu_nm' => '노원구'],
    '11380' => ['sido_nm' => '서울특별시', 'sigungu_nm' => '은평구'],
    '11410' => ['sido_nm' => '서울특별시', 'sigungu_nm' => '서대문구'],
    '11440' => ['sido_nm' => '서울특별시', 'sigungu_nm' => '마포구'],
    '11470' => ['sido_nm' => '서울특별시', 'sigungu_nm' => '양천구'],
    '11500' => ['sido_nm' => '서울특별시', 'sigungu_nm' => '강서구'],
    '11530' => ['sido_nm' => '서울특별시', 'sigungu_nm' => '구로구'],
    '11545' => ['sido_nm' => '서울특별시', 'sigungu_nm' => '금천구'],
    '11560' => ['sido_nm' => '서울특별시', 'sigungu_nm' => '영등포구'],
    '11590' => ['sido_nm' => '서울특별시', 'sigungu_nm' => '동작구'],
    '11620' => ['sido_nm' => '서울특별시', 'sigungu_nm' => '관악구'],
    '11650' => ['sido_nm' => '서울특별시', 'sigungu_nm' => '서초구'],
    '11680' => ['sido_nm' => '서울특별시', 'sigungu_nm' => '강남구'],
    '11710' => ['sido_nm' => '서울특별시', 'sigungu_nm' => '송파구'],
    '11740' => ['sido_nm' => '서울특별시', 'sigungu_nm' => '강동구'],
    '26110' => ['sido_nm' => '부산광역시', 'sigungu_nm' => '중구'],
    '26140' => ['sido_nm' => '부산광역시', 'sigungu_nm' => '서구'],
    '26170' => ['sido_nm' => '부산광역시', 'sigungu_nm' => '동구'],
    '26200' => ['sido_nm' => '부산광역시', 'sigungu_nm' => '영도구'],
    '26230' => ['sido_nm' => '부산광역시', 'sigungu_nm' => '부산진구'],
    '26260' => ['sido_nm' => '부산광역시', 'sigungu_nm' => '동래구'],
    '26290' => ['sido_nm' => '부산광역시', 'sigungu_nm' => '남구'],
    '26320' => ['sido_nm' => '부산광역시', 'sigungu_nm' => '북구'],
    '26350' => ['sido_nm' => '부산광역시', 'sigungu_nm' => '해운대구'],
    '26380' => ['sido_nm' => '부산광역시', 'sigungu_nm' => '사하구'],
    '26410' => ['sido_nm' => '부산광역시', 'sigungu_nm' => '금정구'],
    '26440' => ['sido_nm' => '부산광역시', 'sigungu_nm' => '강서구'],
    '26470' => ['sido_nm' => '부산광역시', 'sigungu_nm' => '연제구'],
    '26500' => ['sido_nm' => '부산광역시', 'sigungu_nm' => '수영구'],
    '26530' => ['sido_nm' => '부산광역시', 'sigungu_nm' => '사상구'],
    '26710' => ['sido_nm' => '부산광역시', 'sigungu_nm' => '기장군'],
    '27110' => ['sido_nm' => '대구광역시', 'sigungu_nm' => '중구'],
    '27140' => ['sido_nm' => '대구광역시', 'sigungu_nm' => '동구'],
    '27170' => ['sido_nm' => '대구광역시', 'sigungu_nm' => '서구'],
    '27200' => ['sido_nm' => '대구광역시', 'sigungu_nm' => '남구'],
    '27230' => ['sido_nm' => '대구광역시', 'sigungu_nm' => '북구'],
    '27260' => ['sido_nm' => '대구광역시', 'sigungu_nm' => '수성구'],
    '27290' => ['sido_nm' => '대구광역시', 'sigungu_nm' => '달서구'],
    '27710' => ['sido_nm' => '대구광역시', 'sigungu_nm' => '달성군'],
    '27720' => ['sido_nm' => '대구광역시', 'sigungu_nm' => '군위군'],
    '28110' => ['sido_nm' => '인천광역시', 'sigungu_nm' => '중구'],
    '28140' => ['sido_nm' => '인천광역시', 'sigungu_nm' => '동구'],
    '28177' => ['sido_nm' => '인천광역시', 'sigungu_nm' => '미추홀구'],
    '28185' => ['sido_nm' => '인천광역시', 'sigungu_nm' => '연수구'],
    '28200' => ['sido_nm' => '인천광역시', 'sigungu_nm' => '남동구'],
    '28237' => ['sido_nm' => '인천광역시', 'sigungu_nm' => '부평구'],
    '28245' => ['sido_nm' => '인천광역시', 'sigungu_nm' => '계양구'],
    '28260' => ['sido_nm' => '인천광역시', 'sigungu_nm' => '서구'],
    '28710' => ['sido_nm' => '인천광역시', 'sigungu_nm' => '강화군'],
    '28720' => ['sido_nm' => '인천광역시', 'sigungu_nm' => '옹진군'],
    '29110' => ['sido_nm' => '광주광역시', 'sigungu_nm' => '동구'],
    '29140' => ['sido_nm' => '광주광역시', 'sigungu_nm' => '서구'],
    '29155' => ['sido_nm' => '광주광역시', 'sigungu_nm' => '남구'],
    '29170' => ['sido_nm' => '광주광역시', 'sigungu_nm' => '북구'],
    '29200' => ['sido_nm' => '광주광역시', 'sigungu_nm' => '광산구'],
    '30110' => ['sido_nm' => '대전광역시', 'sigungu_nm' => '동구'],
    '30140' => ['sido_nm' => '대전광역시', 'sigungu_nm' => '중구'],
    '30170' => ['sido_nm' => '대전광역시', 'sigungu_nm' => '서구'],
    '30200' => ['sido_nm' => '대전광역시', 'sigungu_nm' => '유성구'],
    '30230' => ['sido_nm' => '대전광역시', 'sigungu_nm' => '대덕구'],
    '31110' => ['sido_nm' => '울산광역시', 'sigungu_nm' => '중구'],
    '31140' => ['sido_nm' => '울산광역시', 'sigungu_nm' => '남구'],
    '31170' => ['sido_nm' => '울산광역시', 'sigungu_nm' => '동구'],
    '31200' => ['sido_nm' => '울산광역시', 'sigungu_nm' => '북구'],
    '31710' => ['sido_nm' => '울산광역시', 'sigungu_nm' => '울주군'],
    '36110' => ['sido_nm' => '세종특별자치시', 'sigungu_nm' => '세종시'],
    '41111' => ['sido_nm' => '경기도', 'sigungu_nm' => '수원시 장안구'],
    '41113' => ['sido_nm' => '경기도', 'sigungu_nm' => '수원시 권선구'],
    '41115' => ['sido_nm' => '경기도', 'sigungu_nm' => '수원시 팔달구'],
    '41117' => ['sido_nm' => '경기도', 'sigungu_nm' => '수원시 영통구'],
    '41131' => ['sido_nm' => '경기도', 'sigungu_nm' => '성남시 수정구'],
    '41133' => ['sido_nm' => '경기도', 'sigungu_nm' => '성남시 중원구'],
    '41135' => ['sido_nm' => '경기도', 'sigungu_nm' => '성남시 분당구'],
    '41150' => ['sido_nm' => '경기도', 'sigungu_nm' => '의정부시'],
    '41171' => ['sido_nm' => '경기도', 'sigungu_nm' => '안양시 만안구'],
    '41173' => ['sido_nm' => '경기도', 'sigungu_nm' => '안양시 동안구'],
    '41192' => ['sido_nm' => '경기도', 'sigungu_nm' => '부천시 오정구'],
    '41194' => ['sido_nm' => '경기도', 'sigungu_nm' => '부천시 소사구'],
    '41196' => ['sido_nm' => '경기도', 'sigungu_nm' => '부천시 원미구'],
    '41210' => ['sido_nm' => '경기도', 'sigungu_nm' => '광명시'],
    '41220' => ['sido_nm' => '경기도', 'sigungu_nm' => '평택시'],
    '41250' => ['sido_nm' => '경기도', 'sigungu_nm' => '동두천시'],
    '41271' => ['sido_nm' => '경기도', 'sigungu_nm' => '안산시 상록구'],
    '41273' => ['sido_nm' => '경기도', 'sigungu_nm' => '안산시 단원구'],
    '41281' => ['sido_nm' => '경기도', 'sigungu_nm' => '고양시 덕양구'],
    '41285' => ['sido_nm' => '경기도', 'sigungu_nm' => '고양시 일산동구'],
    '41287' => ['sido_nm' => '경기도', 'sigungu_nm' => '고양시 일산서구'],
    '41290' => ['sido_nm' => '경기도', 'sigungu_nm' => '과천시'],
    '41310' => ['sido_nm' => '경기도', 'sigungu_nm' => '구리시'],
    '41360' => ['sido_nm' => '경기도', 'sigungu_nm' => '남양주시'],
    '41370' => ['sido_nm' => '경기도', 'sigungu_nm' => '오산시'],
    '41390' => ['sido_nm' => '경기도', 'sigungu_nm' => '시흥시'],
    '41410' => ['sido_nm' => '경기도', 'sigungu_nm' => '군포시'],
    '41430' => ['sido_nm' => '경기도', 'sigungu_nm' => '의왕시'],
    '41450' => ['sido_nm' => '경기도', 'sigungu_nm' => '하남시'],
    '41461' => ['sido_nm' => '경기도', 'sigungu_nm' => '용인시 처인구'],
    '41463' => ['sido_nm' => '경기도', 'sigungu_nm' => '용인시 기흥구'],
    '41465' => ['sido_nm' => '경기도', 'sigungu_nm' => '용인시 수지구'],
    '41480' => ['sido_nm' => '경기도', 'sigungu_nm' => '파주시'],
    '41500' => ['sido_nm' => '경기도', 'sigungu_nm' => '이천시'],
    '41550' => ['sido_nm' => '경기도', 'sigungu_nm' => '안성시'],
    '41570' => ['sido_nm' => '경기도', 'sigungu_nm' => '김포시'],
    '41590' => ['sido_nm' => '경기도', 'sigungu_nm' => '화성시'],
    '41610' => ['sido_nm' => '경기도', 'sigungu_nm' => '광주시'],
    '41630' => ['sido_nm' => '경기도', 'sigungu_nm' => '양주시'],
    '41650' => ['sido_nm' => '경기도', 'sigungu_nm' => '포천시'],
    '41670' => ['sido_nm' => '경기도', 'sigungu_nm' => '여주시'],
    '41800' => ['sido_nm' => '경기도', 'sigungu_nm' => '연천군'],
    '41820' => ['sido_nm' => '경기도', 'sigungu_nm' => '가평군'],
    '41830' => ['sido_nm' => '경기도', 'sigungu_nm' => '양평군'],
    '43111' => ['sido_nm' => '충청북도', 'sigungu_nm' => '청주시 상당구'],
    '43112' => ['sido_nm' => '충청북도', 'sigungu_nm' => '청주시 서원구'],
    '43113' => ['sido_nm' => '충청북도', 'sigungu_nm' => '청주시 흥덕구'],
    '43114' => ['sido_nm' => '충청북도', 'sigungu_nm' => '청주시 청원구'],
    '43130' => ['sido_nm' => '충청북도', 'sigungu_nm' => '충주시'],
    '43150' => ['sido_nm' => '충청북도', 'sigungu_nm' => '제천시'],
    '43720' => ['sido_nm' => '충청북도', 'sigungu_nm' => '보은군'],
    '43730' => ['sido_nm' => '충청북도', 'sigungu_nm' => '옥천군'],
    '43740' => ['sido_nm' => '충청북도', 'sigungu_nm' => '영동군'],
    '43745' => ['sido_nm' => '충청북도', 'sigungu_nm' => '증평군'],
    '43750' => ['sido_nm' => '충청북도', 'sigungu_nm' => '진천군'],
    '43760' => ['sido_nm' => '충청북도', 'sigungu_nm' => '괴산군'],
    '43770' => ['sido_nm' => '충청북도', 'sigungu_nm' => '음성군'],
    '43800' => ['sido_nm' => '충청북도', 'sigungu_nm' => '단양군'],
    '44131' => ['sido_nm' => '충청남도', 'sigungu_nm' => '천안시 동남구'],
    '44133' => ['sido_nm' => '충청남도', 'sigungu_nm' => '천안시 서북구'],
    '44150' => ['sido_nm' => '충청남도', 'sigungu_nm' => '공주시'],
    '44180' => ['sido_nm' => '충청남도', 'sigungu_nm' => '보령시'],
    '44200' => ['sido_nm' => '충청남도', 'sigungu_nm' => '아산시'],
    '44210' => ['sido_nm' => '충청남도', 'sigungu_nm' => '서산시'],
    '44230' => ['sido_nm' => '충청남도', 'sigungu_nm' => '논산시'],
    '44250' => ['sido_nm' => '충청남도', 'sigungu_nm' => '계룡시'],
    '44270' => ['sido_nm' => '충청남도', 'sigungu_nm' => '당진시'],
    '44710' => ['sido_nm' => '충청남도', 'sigungu_nm' => '금산군'],
    '44760' => ['sido_nm' => '충청남도', 'sigungu_nm' => '부여군'],
    '44770' => ['sido_nm' => '충청남도', 'sigungu_nm' => '서천군'],
    '44790' => ['sido_nm' => '충청남도', 'sigungu_nm' => '청양군'],
    '44800' => ['sido_nm' => '충청남도', 'sigungu_nm' => '홍성군'],
    '44810' => ['sido_nm' => '충청남도', 'sigungu_nm' => '예산군'],
    '44825' => ['sido_nm' => '충청남도', 'sigungu_nm' => '태안군'],
    '46110' => ['sido_nm' => '전라남도', 'sigungu_nm' => '목포시'],
    '46130' => ['sido_nm' => '전라남도', 'sigungu_nm' => '여수시'],
    '46150' => ['sido_nm' => '전라남도', 'sigungu_nm' => '순천시'],
    '46170' => ['sido_nm' => '전라남도', 'sigungu_nm' => '나주시'],
    '46230' => ['sido_nm' => '전라남도', 'sigungu_nm' => '광양시'],
    '46710' => ['sido_nm' => '전라남도', 'sigungu_nm' => '담양군'],
    '46720' => ['sido_nm' => '전라남도', 'sigungu_nm' => '곡성군'],
    '46730' => ['sido_nm' => '전라남도', 'sigungu_nm' => '구례군'],
    '46770' => ['sido_nm' => '전라남도', 'sigungu_nm' => '고흥군'],
    '46780' => ['sido_nm' => '전라남도', 'sigungu_nm' => '보성군'],
    '46790' => ['sido_nm' => '전라남도', 'sigungu_nm' => '화순군'],
    '46800' => ['sido_nm' => '전라남도', 'sigungu_nm' => '장흥군'],
    '46810' => ['sido_nm' => '전라남도', 'sigungu_nm' => '강진군'],
    '46820' => ['sido_nm' => '전라남도', 'sigungu_nm' => '해남군'],
    '46830' => ['sido_nm' => '전라남도', 'sigungu_nm' => '영암군'],
    '46840' => ['sido_nm' => '전라남도', 'sigungu_nm' => '무안군'],
    '46860' => ['sido_nm' => '전라남도', 'sigungu_nm' => '함평군'],
    '46870' => ['sido_nm' => '전라남도', 'sigungu_nm' => '영광군'],
    '46880' => ['sido_nm' => '전라남도', 'sigungu_nm' => '장성군'],
    '46890' => ['sido_nm' => '전라남도', 'sigungu_nm' => '완도군'],
    '46900' => ['sido_nm' => '전라남도', 'sigungu_nm' => '진도군'],
    '46910' => ['sido_nm' => '전라남도', 'sigungu_nm' => '신안군'],
    '47111' => ['sido_nm' => '경상북도', 'sigungu_nm' => '포항시 남구'],
    '47113' => ['sido_nm' => '경상북도', 'sigungu_nm' => '포항시 북구'],
    '47130' => ['sido_nm' => '경상북도', 'sigungu_nm' => '경주시'],
    '47150' => ['sido_nm' => '경상북도', 'sigungu_nm' => '김천시'],
    '47170' => ['sido_nm' => '경상북도', 'sigungu_nm' => '안동시'],
    '47190' => ['sido_nm' => '경상북도', 'sigungu_nm' => '구미시'],
    '47210' => ['sido_nm' => '경상북도', 'sigungu_nm' => '영주시'],
    '47230' => ['sido_nm' => '경상북도', 'sigungu_nm' => '영천시'],
    '47250' => ['sido_nm' => '경상북도', 'sigungu_nm' => '상주시'],
    '47280' => ['sido_nm' => '경상북도', 'sigungu_nm' => '문경시'],
    '47290' => ['sido_nm' => '경상북도', 'sigungu_nm' => '경산시'],
    '47730' => ['sido_nm' => '경상북도', 'sigungu_nm' => '의성군'],
    '47750' => ['sido_nm' => '경상북도', 'sigungu_nm' => '청송군'],
    '47760' => ['sido_nm' => '경상북도', 'sigungu_nm' => '영양군'],
    '47770' => ['sido_nm' => '경상북도', 'sigungu_nm' => '영덕군'],
    '47820' => ['sido_nm' => '경상북도', 'sigungu_nm' => '청도군'],
    '47830' => ['sido_nm' => '경상북도', 'sigungu_nm' => '고령군'],
    '47840' => ['sido_nm' => '경상북도', 'sigungu_nm' => '성주군'],
    '47850' => ['sido_nm' => '경상북도', 'sigungu_nm' => '칠곡군'],
    '47900' => ['sido_nm' => '경상북도', 'sigungu_nm' => '예천군'],
    '47920' => ['sido_nm' => '경상북도', 'sigungu_nm' => '봉화군'],
    '47930' => ['sido_nm' => '경상북도', 'sigungu_nm' => '울진군'],
    '47940' => ['sido_nm' => '경상북도', 'sigungu_nm' => '울릉군'],
    '48121' => ['sido_nm' => '경상남도', 'sigungu_nm' => '창원시 의창구'],
    '48123' => ['sido_nm' => '경상남도', 'sigungu_nm' => '창원시 성산구'],
    '48125' => ['sido_nm' => '경상남도', 'sigungu_nm' => '창원시 마산합포구'],
    '48127' => ['sido_nm' => '경상남도', 'sigungu_nm' => '창원시 마산회원구'],
    '48129' => ['sido_nm' => '경상남도', 'sigungu_nm' => '창원시 진해구'],
    '48170' => ['sido_nm' => '경상남도', 'sigungu_nm' => '진주시'],
    '48220' => ['sido_nm' => '경상남도', 'sigungu_nm' => '통영시'],
    '48240' => ['sido_nm' => '경상남도', 'sigungu_nm' => '사천시'],
    '48250' => ['sido_nm' => '경상남도', 'sigungu_nm' => '김해시'],
    '48270' => ['sido_nm' => '경상남도', 'sigungu_nm' => '밀양시'],
    '48310' => ['sido_nm' => '경상남도', 'sigungu_nm' => '거제시'],
    '48330' => ['sido_nm' => '경상남도', 'sigungu_nm' => '양산시'],
    '48720' => ['sido_nm' => '경상남도', 'sigungu_nm' => '의령군'],
    '48730' => ['sido_nm' => '경상남도', 'sigungu_nm' => '함안군'],
    '48740' => ['sido_nm' => '경상남도', 'sigungu_nm' => '창녕군'],
    '48820' => ['sido_nm' => '경상남도', 'sigungu_nm' => '고성군'],
    '48840' => ['sido_nm' => '경상남도', 'sigungu_nm' => '남해군'],
    '48850' => ['sido_nm' => '경상남도', 'sigungu_nm' => '하동군'],
    '48860' => ['sido_nm' => '경상남도', 'sigungu_nm' => '산청군'],
    '48870' => ['sido_nm' => '경상남도', 'sigungu_nm' => '함양군'],
    '48880' => ['sido_nm' => '경상남도', 'sigungu_nm' => '거창군'],
    '48890' => ['sido_nm' => '경상남도', 'sigungu_nm' => '합천군'],
    '50110' => ['sido_nm' => '제주특별자치도', 'sigungu_nm' => '제주시'],
    '50130' => ['sido_nm' => '제주특별자치도', 'sigungu_nm' => '서귀포시'],
    '51110' => ['sido_nm' => '강원특별자치도', 'sigungu_nm' => '춘천시'],
    '51130' => ['sido_nm' => '강원특별자치도', 'sigungu_nm' => '원주시'],
    '51150' => ['sido_nm' => '강원특별자치도', 'sigungu_nm' => '강릉시'],
    '51170' => ['sido_nm' => '강원특별자치도', 'sigungu_nm' => '동해시'],
    '51190' => ['sido_nm' => '강원특별자치도', 'sigungu_nm' => '태백시'],
    '51210' => ['sido_nm' => '강원특별자치도', 'sigungu_nm' => '속초시'],
    '51230' => ['sido_nm' => '강원특별자치도', 'sigungu_nm' => '삼척시'],
    '51720' => ['sido_nm' => '강원특별자치도', 'sigungu_nm' => '홍천군'],
    '51730' => ['sido_nm' => '강원특별자치도', 'sigungu_nm' => '횡성군'],
    '51750' => ['sido_nm' => '강원특별자치도', 'sigungu_nm' => '영월군'],
    '51760' => ['sido_nm' => '강원특별자치도', 'sigungu_nm' => '평창군'],
    '51770' => ['sido_nm' => '강원특별자치도', 'sigungu_nm' => '정선군'],
    '51780' => ['sido_nm' => '강원특별자치도', 'sigungu_nm' => '철원군'],
    '51790' => ['sido_nm' => '강원특별자치도', 'sigungu_nm' => '화천군'],
    '51800' => ['sido_nm' => '강원특별자치도', 'sigungu_nm' => '양구군'],
    '51810' => ['sido_nm' => '강원특별자치도', 'sigungu_nm' => '인제군'],
    '51820' => ['sido_nm' => '강원특별자치도', 'sigungu_nm' => '고성군'],
    '51830' => ['sido_nm' => '강원특별자치도', 'sigungu_nm' => '양양군'],
    '52111' => ['sido_nm' => '전북특별자치도', 'sigungu_nm' => '전주시 완산구'],
    '52113' => ['sido_nm' => '전북특별자치도', 'sigungu_nm' => '전주시 덕진구'],
    '52130' => ['sido_nm' => '전북특별자치도', 'sigungu_nm' => '군산시'],
    '52140' => ['sido_nm' => '전북특별자치도', 'sigungu_nm' => '익산시'],
    '52180' => ['sido_nm' => '전북특별자치도', 'sigungu_nm' => '정읍시'],
    '52190' => ['sido_nm' => '전북특별자치도', 'sigungu_nm' => '남원시'],
    '52210' => ['sido_nm' => '전북특별자치도', 'sigungu_nm' => '김제시'],
    '52710' => ['sido_nm' => '전북특별자치도', 'sigungu_nm' => '완주군'],
    '52720' => ['sido_nm' => '전북특별자치도', 'sigungu_nm' => '진안군'],
    '52730' => ['sido_nm' => '전북특별자치도', 'sigungu_nm' => '무주군'],
    '52740' => ['sido_nm' => '전북특별자치도', 'sigungu_nm' => '장수군'],
    '52750' => ['sido_nm' => '전북특별자치도', 'sigungu_nm' => '임실군'],
    '52770' => ['sido_nm' => '전북특별자치도', 'sigungu_nm' => '순창군'],
    '52790' => ['sido_nm' => '전북특별자치도', 'sigungu_nm' => '고창군'],
    '52800' => ['sido_nm' => '전북특별자치도', 'sigungu_nm' => '부안군'],
  ];

  /**
   * 코드로 지역 정보 조회
   */
  public static function get(string $lawdCd): ?array
  {
    return self::REGIONS[$lawdCd] ?? null;
  }

  /**
   * 전체 코드 배열 반환
   */
  public static function all(): array
  {
    return self::REGIONS;
  }

  /**
   * 전체 코드 키만 반환
   */
  public static function codes(): array
  {
    return array_keys(self::REGIONS);
  }
}
